version: "3.4"
services:
    gitlab:
        image: 'gitlab/gitlab-ce:latest'
        restart: unless-stopped
        hostname: '${GITLAB_FQDN}'
        environment:
            GITLAB_OMNIBUS_CONFIG: |
                external_url '${GITLAB_BASEURL}'
                gitlab_rails['initial_root_password'] = '${GITLAB_INIT_ROOTPW}'
                # Add any other gitlab.rb configuration here, each on its own line
        ports:
            - "8085:8085"
        volumes:
            - '$YOUR_LOCAL_DIR/gitlab/config:/etc/gitlab'
            - '$YOUR_LOCAL_DIR/gitlab/logs:/var/log/gitlab'
            - '$YOUR_LOCAL_DIR/gitlab/data:/var/opt/gitlab'
    misp:
        build: misp-docker/web
        depends_on:
            - misp-db
        image: misp:latest
        restart: unless-stopped
        ports:
            - "8087:443"
        volumes:
            - /dev/urandom:/dev/random
            - ${YOUR_LOCAL_DIR}/misp/web:/var/www/MISP
        environment:
            - MYSQL_HOST=${MYSQL_HOST}
            - MYSQL_DATABASE=${MYSQL_DATABASE}
            - MYSQL_USER=${MYSQL_USER}
            - MYSQL_PASSWORD=${MYSQL_PASSWORD}
            - MISP_ADMIN_EMAIL=${MISP_ADMIN_EMAIL}
            - MISP_ADMIN_PASSPHRASE=${MISP_ADMIN_PASSPHRASE}
            - MISP_BASEURL=${MISP_BASEURL}
            - POSTFIX_RELAY_HOST=${POSTFIX_RELAY_HOST}
            - TIMEZONE=${TIMEZONE}
    
    misp-db:
        image: mysql/mysql-server:5.7
        restart: unless-stopped
        volumes:
            - ${YOUR_LOCAL_DIR}/db:/var/lib/mysql
        environment:
            - MYSQL_DATABASE=${MYSQL_DATABASE}
            - MYSQL_USER=${MYSQL_USER}
            - MYSQL_PASSWORD=${MYSQL_PASSWORD}
            - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}