name:   Dev Workflow
on:
    push:
        branches:
            - dev
    pull_request:
        branches:
            - dev
            - master
jobs:
    pylint:
        runs-on: ubuntu-latest
        strategy:
            matrix:
                python-version: [3.9]
        steps:
            - name: Install Python dependencies
              run: |
                python -m pip install --upgrade pip
                pip install pylint
                ls
            - name: "Running the linter"
              run: pylint ./*

