name:   Dev Workflow
on:
    push:
        branches:
            - dev
    pull_request:
        branches:
            - dev
            - master
jobs:
    linter:
        runs-on: ubuntu-latest
        strategy:
            matrix:
                python-version: [3.9]
        steps:
            - name: Install Python dependencies
              uses: py-actions/py-dependency-install@v2
              with:
                update-pip: "false"
                update-setuptools: "false"
                update-wheel: "false"
            
            - name: "Running the linter"
              run: pylint *

