name:   Dev Workflow
on:
    push:
        branches:
            - dev
    pull_request:
        branches:
            - dev
            - master
jobs:
    linter:
        runs-on: ubuntu-latest
        strategy:
            matrix:
                python-version: [3.9]
        steps:
            - name: Install Python dependencies
              run: |
                python -m pip install --upgrade pip
                pip install flake8 pytest
                if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

            - name: "Running the linter"
              run: pylint *

